/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define COMPUTE 3
#define COMPUTE_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define GET_DATETIME 1
extern  char ** get_datetime_2(void *, CLIENT *);
extern  char ** get_datetime_2_svc(void *, struct svc_req *);
extern int compute_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_DATETIME 1
extern  char ** get_datetime_2();
extern  char ** get_datetime_2_svc();
extern int compute_2_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATE_H_RPCGEN */
